spring.application.name=db-navigator-demo

#PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/dbnavigator
spring.datasource.username=dbuser
spring.datasource.password=dbpass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Actuator (Health Check)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# Server
server.port=8080
